# Generated by Django 3.1.6 on 2021-02-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='detalhes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='nome',
            field=models.CharField(help_text='Digite um nome fácil', max_length=50),
        ),
    ]
