# Generated by Django 3.1.6 on 2021-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20210219_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Número'),
        ),
    ]
